"""empty message

Revision ID: 10186c00258b
Revises: 343e5bb34d6a
Create Date: 2014-12-29 16:41:12.002860

"""

# revision identifiers, used by Alembic.
revision = '10186c00258b'
down_revision = '343e5bb34d6a'

from alembic import op
import sqlalchemy as sa


def upgrade():
### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.Text(), nullable=True),
    sa.Column('project_desc', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_projects_end_date'), 'projects', ['end_date'], unique=False)
    op.create_index(op.f('ix_projects_project_name'), 'projects', ['project_name'], unique=False)
    op.create_index(op.f('ix_projects_start_date'), 'projects', ['start_date'], unique=False)
    op.create_table('project_user_map',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_index(op.f('ix_project_user_map_project_id'), 'project_user_map', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_user_map_user_id'), 'project_user_map', ['user_id'], unique=False)
    # op.drop_table('sqlite_sequence')

    op.drop_table('tasks')
    op.create_table('tasks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('task_name', sa.Text(), nullable=True),
                    sa.Column('task_desc', sa.Text(), nullable=True),
                    sa.Column('start_date', sa.Date(), nullable=False),
                    sa.Column('end_date', sa.Date(), nullable=True),
                    sa.Column('creator_id', sa.Integer(), nullable=True),
                    sa.Column('case_id', sa.Integer(), nullable=True),
                    sa.Column('project_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
                    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['project_id'],['projects.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_tasks_end_date'), 'tasks', ['end_date'],
                    unique=False)
    op.create_index(op.f('ix_tasks_start_date'), 'tasks', ['start_date'],
                    unique=False)
    op.create_index(op.f('ix_tasks_task_name'), 'tasks', ['task_name'],
                    unique=False)
    ### end Alembic commands ###


def downgrade():
### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.create_table('tasks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('task_name', sa.Text(), nullable=True),
                    sa.Column('task_desc', sa.Text(), nullable=True),
                    sa.Column('start_date', sa.Date(), nullable=False),
                    sa.Column('end_date', sa.Date(), nullable=True),
                    sa.Column('creator_id', sa.Integer(), nullable=True),
                    sa.Column('case_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
                    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_tasks_end_date'), 'tasks', ['end_date'],
                    unique=False)
    op.create_index(op.f('ix_tasks_start_date'), 'tasks', ['start_date'],
                    unique=False)
    op.create_index(op.f('ix_tasks_task_name'), 'tasks', ['task_name'],
                    unique=False)

    # op.create_table('sqlite_sequence',
    # sa.Column('name', sa.NullType(), nullable=True),
    # sa.Column('seq', sa.NullType(), nullable=True)
    # )
    op.drop_index(op.f('ix_project_user_map_user_id'), table_name='project_user_map')
    op.drop_index(op.f('ix_project_user_map_project_id'), table_name='project_user_map')
    op.drop_table('project_user_map')
    op.drop_index(op.f('ix_projects_start_date'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_end_date'), table_name='projects')
    op.drop_table('projects')
    ### end Alembic commands ###
