"""empty message

Revision ID: 1ca97be2189b
Revises: 417ba09ee0ec
Create Date: 2014-11-24 16:41:35.178000

"""

# revision identifiers, used by Alembic.
revision = '1ca97be2189b'
down_revision = '417ba09ee0ec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    op.add_column('case_assignments', sa.Column('primary', sa.Boolean(), nullable=True))
    op.add_column('case_assignments', sa.Column('secondary', sa.Boolean(), nullable=True))

    # We need to drop the table to alter it...
    op.drop_table('cases')
    op.create_table('cases',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('crd_number', sa.Integer(), nullable=False),
                    sa.Column('start_date', sa.Date(), nullable=False),
                    sa.Column('end_date', sa.Date(), nullable=True),
                    sa.Column('case_type_id', sa.String(length=15), nullable=False),
                    sa.Column('region_id', sa.String(length=4), nullable=False),
                    sa.Column('mars_risk_score', sa.Integer(), nullable=True),
                    sa.Column('qau_risk_score', sa.Integer(), nullable=True),
                    sa.Column('examiner_risk_score', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['case_type_id'], ['case_types.id'], ),
                    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('secondary_id', sa.INTEGER(), nullable=False))
    op.add_column('cases', sa.Column('primary_id', sa.INTEGER(), nullable=False))
    op.drop_column('case_assignments', 'secondary')
    op.drop_column('case_assignments', 'primary')
    ### end Alembic commands ###
