"""empty message

Revision ID: 2c3628cd7812
Revises: 324c565bf711
Create Date: 2014-12-03 12:13:52.247692

"""

# revision identifiers, used by Alembic.
revision = '2c3628cd7812'
down_revision = '324c565bf711'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
