"""empty message

Revision ID: 324c565bf711
Revises: 1ca97be2189b
Create Date: 2014-11-25 11:06:45.527000

"""

# revision identifiers, used by Alembic.
revision = '324c565bf711'
down_revision = '1ca97be2189b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('case_desc', sa.Text(), nullable=True))
    op.add_column('cases', sa.Column('case_name', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'case_name')
    op.drop_column('cases', 'case_desc')
    ### end Alembic commands ###
