"""empty message

Revision ID: 417ba09ee0ec
Revises: 4110d60e5b47
Create Date: 2014-11-19 20:53:53.422813

"""

# revision identifiers, used by Alembic.
revision = '417ba09ee0ec'
down_revision = '4110d60e5b47'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_assignments',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.add_column(u'cases', sa.Column('case_desc', sa.Text(), nullable=True))
    op.add_column(u'cases', sa.Column('case_name', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'cases', 'case_name')
    op.drop_column(u'cases', 'case_desc')
    op.drop_table('case_assignments')
    ### end Alembic commands ###
