"""empty message

Revision ID: 52ae2f07ac3a
Revises: 21224843faf
Create Date: 2014-12-08 16:17:50.324073

"""

# revision identifiers, used by Alembic.
revision = '52ae2f07ac3a'
down_revision = '21224843faf'

from alembic import op
import sqlalchemy as sa


def upgrade():
  # ## commands auto generated by Alembic - please adjust! ###
  # op.drop_table('sqlite_sequence')
  op.drop_table('case_staff_map')
  op.create_table('case_staff_map',
                  sa.Column('id', sa.Integer(), nullable=False),
                  sa.Column('user_id', sa.Integer(), nullable=True),
                  sa.Column('case_id', sa.Integer(), nullable=True),
                  sa.Column('primary', sa.Boolean(), nullable=True),
                  sa.Column('secondary', sa.Boolean(), nullable=True),
                  sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
                  sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                  sa.PrimaryKeyConstraint('id'),
                  sqlite_autoincrement=True)
  op.create_index(op.f('ix_case_staff_map_case_id'), 'case_staff_map',
                  ['case_id'], unique=False)
  op.create_index(op.f('ix_case_staff_map_user_id'), 'case_staff_map',
                  ['user_id'], unique=False)
  op.add_column('users',
                sa.Column('contract', sa.String(length=20), nullable=True))
  ### end Alembic commands ###


def downgrade():
  # ## commands auto generated by Alembic - please adjust! ###
  op.drop_column('users', 'contract')
  op.drop_column('case_staff_map', 'id')
  # op.create_table('sqlite_sequence',
  # sa.Column('name', sa.NullType(), nullable=True),
  # sa.Column('seq', sa.NullType(), nullable=True)
  # )
  ### end Alembic commands ###
