"""empty message

Revision ID: 554d7eb589fa
Revises: 10186c00258b
Create Date: 2014-12-30 16:37:22.683386

"""

# revision identifiers, used by Alembic.
revision = '554d7eb589fa'
down_revision = '10186c00258b'

from alembic import op
import sqlalchemy as sa


def upgrade():
### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    # with op.batch_alter_table('case_statuses', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_case_statuses_type'), ['type'], unique=True)

    # op.drop_table('sqlite_sequence')

    op.drop_index(op.f('ix_cases_crd_number'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_name'), table_name='cases')
    op.drop_index(op.f('ix_cases_end_date'), table_name='cases')
    op.drop_index(op.f('ix_cases_start_date'), table_name='cases')

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_status_id', sa.Integer(),
                                      nullable=True))
        batch_op.create_foreign_key('fk_cases_case_status_id_case_statuses',
                                    'case_statuses', ['case_status_id'], ['id'])


    op.create_index(op.f('ix_cases_case_name'), 'cases', ['case_name'],
                    unique=False)
    op.create_index(op.f('ix_cases_crd_number'), 'cases', ['crd_number'],
                    unique=False)
    op.create_index(op.f('ix_cases_end_date'), 'cases', ['end_date'],
                    unique=False)
    op.create_index(op.f('ix_cases_start_date'), 'cases', ['start_date'],
                    unique=False)
    op.create_index(op.f('ix_case_statuses_type'), 'case_statuses', ['type'],
                    unique=True)

    ### end Alembic commands ###


def downgrade():
### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cases_case_status_id_case_statuses', type_='foreignkey')
        batch_op.drop_column('case_status_id')

    # op.create_table('sqlite_sequence',
    # sa.Column('name', sa.NullType(), nullable=True),
    # sa.Column('seq', sa.NullType(), nullable=True)
    # )
    with op.batch_alter_table('case_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_statuses_type'))

    op.drop_table('case_statuses')
    ### end Alembic commands ###
