"""empty message

Revision ID: e60c3d8b005
Revises: 52ae2f07ac3a
Create Date: 2014-12-09 15:39:16.272520

"""

# revision identifiers, used by Alembic.
revision = 'e60c3d8b005'
down_revision = '52ae2f07ac3a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('attributes', sa.Text(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_files')
    ### end Alembic commands ###
